name: Java Build Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          mkdir -p out
          javac -d out src/*.java

      - name: Run Java program (optional)
        run: |
          java -cp out Calculator
        continue-on-error: true  # Optional: don't fail if it doesn't run
